import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { auth } from "../firebase.config";
import { reauthenticateWithPopup } from "firebase/auth";
import { useAuth } from "../context/AuthContext";

export default function Home() {
  const router = useRouter();
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");

  const { currentUser, logout } = useAuth();

  const handleLogout = async () => {
    setError("");
    try {
      await logout();
      return router.push("/login");
    } catch (error) {
      setError("Logout Failed");
    }
  };
  useEffect(() => {
    if (!currentUser) {
      router.push("/login");
    }
    setMessage(`Welcome ${currentUser.email}`);
  }, []);
  if (message) {
    setTimeout(() => {
      setMessage("");
    }, 5000);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>NEXT CRUD AUTH App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Home</h1>
        <p className={styles.error}>{error}</p>
        <p className={styles.message}>{message}</p>

        <form className={styles.form}>
          <input type="text" placeholder="Name" className={styles.inputBox} />
          <input type="text" placeholder="Age" className={styles.inputBox} />
          <button className={styles.button} type="submit">
            ADD
          </button>
          <button
            onClick={handleLogout}
            className={styles.button}
            type="submit"
          >
            LOG OUT
          </button>
        </form>
      </main>
    </div>
  );
}
