import Head from "next/head";
import styles from "../styles/Home.module.css";
import { app } from "../firebase.config";
const Login = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>NEXT CRUD AUTH App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Login</h1>
      </main>
    </div>
  );
};

export default Login;
